### ISSUE TITLE
Silent fails for beeminder API calls

### ISSUE THREAD

**Issue by maggiedelano** [maggiedelano/Strict-Workflow-Beeminder#2]
Currently does not notify the user if the beeminder API call fails, nor does the extension try again.

**Comment by DrTall** [comment]
Howdy! I put a bounty on this at bountysource.com half because it would be nice to have this fixed, but thanks for making this in the first place! I've used strict workflow for a while and have been too lazy to do the Beeminder hookup.

**Comment by maggiedelano** [comment]
This is fixed now (#3). Thanks @kbailey4444!
